name: 465_env
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py310haa95532_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.3=py310haa95532_0
  - debugpy=1.8.16=py310h885b0b7_1
  - decorator=5.2.1=py310haa95532_0
  - exceptiongroup=1.3.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - ipykernel=6.31.0=py310h4442805_0
  - ipython=8.30.0=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jupyter_client=8.8.0=py310haa95532_0
  - jupyter_core=5.9.1=py310haa95532_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - parso=0.8.5=py310haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py310haa95532_0
  - prompt-toolkit=3.0.52=py310haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310h02ab6af_1
  - pure_eval=0.2.3=py310haa95532_0
  - pygments=2.19.2=py310haa95532_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - pywin32=311=py310h885b0b7_0
  - pyzmq=27.1.0=py310h7149c55_1
  - setuptools=80.10.1=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py310h02ab6af_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=py310haa95532_0
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - ase==3.27.0
      - beautifulsoup4==4.14.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorspacious==1.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2026.1.2
      - dill==0.4.1
      - distributed==2026.1.2
      - emdfile==0.0.16
      - filelock==3.20.3
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - gdown==5.2.1
      - h5py==3.15.1
      - hdf5plugin==6.0.0
      - hyperspy==2.4.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - locket==1.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpire==2.10.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - natsort==8.4.0
      - ncempy==1.11.1
      - networkx==3.4.2
      - numpy==1.26.4
      - partd==1.4.2
      - pillow==12.1.0
      - pint==0.24.4
      - prettytable==3.17.0
      - py4dstem==0.14.18
      - pyaml==25.7.0
      - pylops==2.6.0
      - pyparsing==3.3.2
      - pysocks==1.7.1
      - python-box==7.3.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rosettasciio==0.12.0
      - scikit-image==0.25.2
      - scikit-learn==1.4.2
      - scikit-optimize==0.10.2
      - scipy==1.15.3
      - sortedcontainers==2.4.0
      - soupsieve==2.8.3
      - sympy==1.14.0
      - tblib==3.2.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - toolz==1.1.0
      - tqdm==4.67.2
      - traits==7.1.0
      - urllib3==2.6.3
      - zict==3.0.0
      - zipp==3.23.0
prefix: D:\Miniconda\envs\465_env
